// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace RioValleyChili.Client.Mvc.Controllers
{
    public partial class ProductionController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProductionController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ProductionController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MillAndWetdownDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MillAndWetdownDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PackScheduleDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PackScheduleDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ProducionResultDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProducionResultDetails);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProductionController Actions { get { return MVC.Production; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Production";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Production";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string MillAndWetdown = "MillAndWetdown";
            public readonly string CreateMillAndWetdown = "CreateMillAndWetdown";
            public readonly string MillAndWetdownDetails = "MillAndWetdownDetails";
            public readonly string PackSchedules = "PackSchedules";
            public readonly string PackScheduleDetails = "PackScheduleDetails";
            public readonly string ProductionResults = "ProductionResults";
            public readonly string ProducionResultDetails = "ProducionResultDetails";
            public readonly string ProductionSchedules = "ProductionSchedules";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string MillAndWetdown = "MillAndWetdown";
            public const string CreateMillAndWetdown = "CreateMillAndWetdown";
            public const string MillAndWetdownDetails = "MillAndWetdownDetails";
            public const string PackSchedules = "PackSchedules";
            public const string PackScheduleDetails = "PackScheduleDetails";
            public const string ProductionResults = "ProductionResults";
            public const string ProducionResultDetails = "ProducionResultDetails";
            public const string ProductionSchedules = "ProductionSchedules";
        }


        static readonly ActionParamsClass_MillAndWetdownDetails s_params_MillAndWetdownDetails = new ActionParamsClass_MillAndWetdownDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MillAndWetdownDetails MillAndWetdownDetailsParams { get { return s_params_MillAndWetdownDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MillAndWetdownDetails
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PackScheduleDetails s_params_PackScheduleDetails = new ActionParamsClass_PackScheduleDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PackScheduleDetails PackScheduleDetailsParams { get { return s_params_PackScheduleDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PackScheduleDetails
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ProducionResultDetails s_params_ProducionResultDetails = new ActionParamsClass_ProducionResultDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ProducionResultDetails ProducionResultDetailsParams { get { return s_params_ProducionResultDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ProducionResultDetails
        {
            public readonly string lot = "lot";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string MillAndWetdown = "MillAndWetdown";
                public readonly string PackSchedules = "PackSchedules";
                public readonly string ProductionResults = "ProductionResults";
                public readonly string ProductionSchedules = "ProductionSchedules";
            }
            public readonly string Index = "~/Views/Production/Index.cshtml";
            public readonly string MillAndWetdown = "~/Views/Production/MillAndWetdown.cshtml";
            public readonly string PackSchedules = "~/Views/Production/PackSchedules.cshtml";
            public readonly string ProductionResults = "~/Views/Production/ProductionResults.cshtml";
            public readonly string ProductionSchedules = "~/Views/Production/ProductionSchedules.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ProductionController : RioValleyChili.Client.Mvc.Controllers.ProductionController
    {
        public T4MVC_ProductionController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MillAndWetdownOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult MillAndWetdown()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MillAndWetdown);
            MillAndWetdownOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateMillAndWetdownOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateMillAndWetdown()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateMillAndWetdown);
            CreateMillAndWetdownOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MillAndWetdownDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult MillAndWetdownDetails(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MillAndWetdownDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            MillAndWetdownDetailsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void PackSchedulesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PackSchedules()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PackSchedules);
            PackSchedulesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PackScheduleDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PackScheduleDetails(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PackScheduleDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PackScheduleDetailsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ProductionResultsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ProductionResults()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProductionResults);
            ProductionResultsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ProducionResultDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string lot);

        [NonAction]
        public override System.Web.Mvc.ActionResult ProducionResultDetails(string lot)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProducionResultDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lot", lot);
            ProducionResultDetailsOverride(callInfo, lot);
            return callInfo;
        }

        [NonAction]
        partial void ProductionSchedulesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ProductionSchedules()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProductionSchedules);
            ProductionSchedulesOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
