// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace RioValleyChili.Client.Mvc.Areas.Reporting.Controllers
{
    public partial class SampleOrderReportingController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SampleOrderReportingController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SampleOrderReportingController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SampleMatchingSummary()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SampleMatchingSummary);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SampleRequest()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SampleRequest);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SampleOrderReportingController Actions { get { return MVC.Reporting.SampleOrderReporting; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Reporting";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "SampleOrderReporting";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "SampleOrderReporting";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string SampleMatchingSummary = "SampleMatchingSummary";
            public readonly string SampleRequest = "SampleRequest";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string SampleMatchingSummary = "SampleMatchingSummary";
            public const string SampleRequest = "SampleRequest";
        }


        static readonly ActionParamsClass_SampleMatchingSummary s_params_SampleMatchingSummary = new ActionParamsClass_SampleMatchingSummary();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SampleMatchingSummary SampleMatchingSummaryParams { get { return s_params_SampleMatchingSummary; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SampleMatchingSummary
        {
            public readonly string sampleOrderKey = "sampleOrderKey";
            public readonly string itemKey = "itemKey";
        }
        static readonly ActionParamsClass_SampleRequest s_params_SampleRequest = new ActionParamsClass_SampleRequest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SampleRequest SampleRequestParams { get { return s_params_SampleRequest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SampleRequest
        {
            public readonly string sampleOrderKey = "sampleOrderKey";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SampleOrderReportingController : RioValleyChili.Client.Mvc.Areas.Reporting.Controllers.SampleOrderReportingController
    {
        public T4MVC_SampleOrderReportingController() : base(Dummy.Instance) { }

        [NonAction]
        partial void SampleMatchingSummaryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string sampleOrderKey, string itemKey);

        [NonAction]
        public override System.Web.Mvc.ActionResult SampleMatchingSummary(string sampleOrderKey, string itemKey)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SampleMatchingSummary);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sampleOrderKey", sampleOrderKey);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "itemKey", itemKey);
            SampleMatchingSummaryOverride(callInfo, sampleOrderKey, itemKey);
            return callInfo;
        }

        [NonAction]
        partial void SampleRequestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string sampleOrderKey);

        [NonAction]
        public override System.Web.Mvc.ActionResult SampleRequest(string sampleOrderKey)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SampleRequest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sampleOrderKey", sampleOrderKey);
            SampleRequestOverride(callInfo, sampleOrderKey);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
