//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioValleyChili.Business.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RioValleyChili.Business.Core.Resources.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Additive Product with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string AdditiveProductNotFound {
            get {
                return ResourceManager.GetString("AdditiveProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Additive Type with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string AdditiveTypeNotFound {
            get {
                return ResourceManager.GetString("AdditiveTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment quantity cannot be zero..
        /// </summary>
        public static string AdjustmentQuantityCannotBeZero {
            get {
                return ResourceManager.GetString("AdjustmentQuantityCannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; requires resolution information..
        /// </summary>
        public static string AttributeDefectRequiresResolution {
            get {
                return ResourceManager.GetString("AttributeDefectRequiresResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Attribute Name with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string AttributeNameNotFound {
            get {
                return ResourceManager.GetString("AttributeNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Attribute Name with Key &apos;{0}&apos; is not valid for a Chile Product..
        /// </summary>
        public static string AttributeNameNotValidForChile {
            get {
                return ResourceManager.GetString("AttributeNameNotValidForChile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Batch Item must have a quantity greater than 0..
        /// </summary>
        public static string BatchItemQuantityRequired {
            get {
                return ResourceManager.GetString("BatchItemQuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create Chile Materials Received record with no Items..
        /// </summary>
        public static string CannotCreateChileReceivedWithNoItems {
            get {
                return ResourceManager.GetString("CannotCreateChileReceivedWithNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete an Inventory Shipment Order that has been Fulfilled..
        /// </summary>
        public static string CannotDeleteFulfilledShipmentOrder {
            get {
                return ResourceManager.GetString("CannotDeleteFulfilledShipmentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete an Inventory Shipment Order that has been Shipped..
        /// </summary>
        public static string CannotDeleteShippedShipmentOrder {
            get {
                return ResourceManager.GetString("CannotDeleteShippedShipmentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pick Inventory for a Customer Order Item with Key &apos;{0}&apos; because it does not exist for this order..
        /// </summary>
        public static string CannotPickForCustomerOrderItem_DoesNotExist {
            get {
                return ResourceManager.GetString("CannotPickForCustomerOrderItem_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pick Inventory for Order Item with Key &apos;{0}&apos; because it does not exist for this order..
        /// </summary>
        public static string CannotPickForOrderItem_DoesNotExist {
            get {
                return ResourceManager.GetString("CannotPickForOrderItem_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pick Inventory for Customer Order with Key &apos;{0}&apos; because it has already been Invoiced..
        /// </summary>
        public static string CannotPickInvoicedCustomerOrder {
            get {
                return ResourceManager.GetString("CannotPickInvoicedCustomerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pick from Lot with Key &apos;{0}&apos; because the it is not Produced..
        /// </summary>
        public static string CannotPickLotNotProduced {
            get {
                return ResourceManager.GetString("CannotPickLotNotProduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pick from Lot with Key &apos;{0}&apos; because it is on Hold &apos;{1}&apos;..
        /// </summary>
        public static string CannotPickLotOnHold {
            get {
                return ResourceManager.GetString("CannotPickLotOnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pick from Lot with Key &apos;{0}&apos; because it is flagged as &apos;{1}&apos;..
        /// </summary>
        public static string CannotPickLotQualityState {
            get {
                return ResourceManager.GetString("CannotPickLotQualityState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify picked inventory for shipment with status &apos;{0}&apos;..
        /// </summary>
        public static string CannotPickShipment {
            get {
                return ResourceManager.GetString("CannotPickShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pick Inventory for Customer Order with Key &apos;{0}&apos; because it has been voided..
        /// </summary>
        public static string CannotPickVoidedCustomerOrder {
            get {
                return ResourceManager.GetString("CannotPickVoidedCustomerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove Customer Order Item(s) because it has been picked. Remove picked items first..
        /// </summary>
        public static string CannotRemovePickedCustomerOrderItem {
            get {
                return ResourceManager.GetString("CannotRemovePickedCustomerOrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Attribute with Key &apos;{0}&apos; can only be set once..
        /// </summary>
        public static string CannotSetAttributeMoreThanOnce {
            get {
                return ResourceManager.GetString("CannotSetAttributeMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set status of Lot with Key &apos;{0}&apos; from &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        public static string CannotSetLotStatus {
            get {
                return ResourceManager.GetString("CannotSetLotStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chile Lot with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ChileLotNotFound {
            get {
                return ResourceManager.GetString("ChileLotNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chile Materials Received record with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ChileMaterialsReceivedNotFound {
            get {
                return ResourceManager.GetString("ChileMaterialsReceivedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Chile Product&apos;s Attribute Range&apos;s Min value cannot be greater than its Max value..
        /// </summary>
        public static string ChileProductAttributeRangeMinGreaterThanMax {
            get {
                return ResourceManager.GetString("ChileProductAttributeRangeMinGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chile Product Attribute Range with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ChileProductAttributeRangeNotFound {
            get {
                return ResourceManager.GetString("ChileProductAttributeRangeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Chile Product must result in the same Lot type..
        /// </summary>
        public static string ChileProductDifferentLotType {
            get {
                return ResourceManager.GetString("ChileProductDifferentLotType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chile Product Ingredient with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ChileProductIngredientNotFound {
            get {
                return ResourceManager.GetString("ChileProductIngredientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chile Product with Key &apos;{0}&apos; is of &apos;{1}&apos; state, but expected &apos;{2}&apos;..
        /// </summary>
        public static string ChileProductInvalidState {
            get {
                return ResourceManager.GetString("ChileProductInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chile Product with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ChileProductNotFound {
            get {
                return ResourceManager.GetString("ChileProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chile Type with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ChileTypeNotFound {
            get {
                return ResourceManager.GetString("ChileTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company Address with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string CompanyAddressNotFound {
            get {
                return ResourceManager.GetString("CompanyAddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string CompanyNotFound {
            get {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company with Key &apos;{0}&apos; is not of type &apos;{1}&apos;..
        /// </summary>
        public static string CompanyNotOfType {
            get {
                return ResourceManager.GetString("CompanyNotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company with Key &apos;{0}&apos; is of type &apos;{1}&apos; but needs to be &apos;{2}&apos;..
        /// </summary>
        public static string CompanyTypeNotCorrect {
            get {
                return ResourceManager.GetString("CompanyTypeNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Types are required..
        /// </summary>
        public static string CompanyTypesRequired {
            get {
                return ResourceManager.GetString("CompanyTypesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contact Address with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ContactAddressNotFound {
            get {
                return ResourceManager.GetString("ContactAddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact with Key &apos;{0}&apos; does not contain a Contact Address with Key &apos;{1}&apos;..
        /// </summary>
        public static string ContactDoesNotContainAddress {
            get {
                return ResourceManager.GetString("ContactDoesNotContainAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contact with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ContactNotFound {
            get {
                return ResourceManager.GetString("ContactNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contact with Key &apos;{0}&apos; does not belong to Customer with Key &apos;{1}&apos;..
        /// </summary>
        public static string ContactNotOfCustomer {
            get {
                return ResourceManager.GetString("ContactNotOfCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new Broker with Key &apos;{0}&apos; is not the Broker for Customer with Key &apos;{1}&apos;..
        /// </summary>
        public static string ContractBrokerIsNotOfCustomer {
            get {
                return ResourceManager.GetString("ContractBrokerIsNotOfCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contract Item with Key &apos;{0}&apos; for Customer with Key &apos;{1}&apos; could not be found..
        /// </summary>
        public static string ContractItemForCustomerNotFound {
            get {
                return ResourceManager.GetString("ContractItemForCustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Items are required for this operation..
        /// </summary>
        public static string ContractItemsRequired {
            get {
                return ResourceManager.GetString("ContractItemsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Term End date &apos;{1}&apos; must be a later date than the Term Begin date &apos;{0}&apos;..
        /// </summary>
        public static string ContractTermMustBeginBeforeEnd {
            get {
                return ResourceManager.GetString("ContractTermMustBeginBeforeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to create a new Production Batch..
        /// </summary>
        public static string CreateProductionBatchFailed {
            get {
                return ResourceManager.GetString("CreateProductionBatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer Contract with Key &apos;{0}&apos; is already completed and cannot be modified..
        /// </summary>
        public static string CustomerContractCompletedCannotChange {
            get {
                return ResourceManager.GetString("CustomerContractCompletedCannotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer Contract with Key &apos;{0}&apos; has order items associated..
        /// </summary>
        public static string CustomerContractHasOrderItems {
            get {
                return ResourceManager.GetString("CustomerContractHasOrderItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer Contract with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string CustomerContractNotFound {
            get {
                return ResourceManager.GetString("CustomerContractNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer Note with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string CustomerNoteNotFound {
            get {
                return ResourceManager.GetString("CustomerNoteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer with Key &apos;{0}&apos; not found..
        /// </summary>
        public static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer with Key &apos;{0}&apos; is not of Broker with Key &apos;{1}&apos;..
        /// </summary>
        public static string CustomerNotOfBroker {
            get {
                return ResourceManager.GetString("CustomerNotOfBroker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer Product Attribute Range with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string CustomerProductAttributeRangeNotFound {
            get {
                return ResourceManager.GetString("CustomerProductAttributeRangeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Spec.
        /// </summary>
        public static string CustomerSpec {
            get {
                return ResourceManager.GetString("CustomerSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dehydrator Company with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string DehydratorCompanyNotFound {
            get {
                return ResourceManager.GetString("DehydratorCompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination location must be in Facility with Key &apos;{0}&apos;..
        /// </summary>
        public static string DestinationLocationMustBelongToFacility {
            get {
                return ResourceManager.GetString("DestinationLocationMustBelongToFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Location required for Picked Inventory Item with Key &apos;{0}&apos;..
        /// </summary>
        public static string DestinationLocationRequiredForPicked {
            get {
                return ResourceManager.GetString("DestinationLocationRequiredForPicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employee found having the Key &quot;{0}&quot;..
        /// </summary>
        public static string EmployeeByKeyNotFound {
            get {
                return ResourceManager.GetString("EmployeeByKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employee was found for the supplied token..
        /// </summary>
        public static string EmployeeByTokenNotFound {
            get {
                return ResourceManager.GetString("EmployeeByTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employee found having the user name &quot;{0}&quot;..
        /// </summary>
        public static string EmployeeByUserNameNotFound {
            get {
                return ResourceManager.GetString("EmployeeByUserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run operation on an empty set..
        /// </summary>
        public static string EmptySet {
            get {
                return ResourceManager.GetString("EmptySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Chile Product Key &apos;{0}&apos; for Contract Item with Key &apos;{1}&apos;, but received &apos;{2}&apos;..
        /// </summary>
        public static string ExpectedChileProductKeyForContractItemNotEqualReceived {
            get {
                return ResourceManager.GetString("ExpectedChileProductKeyForContractItemNotEqualReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The facility &apos;{0}&apos; already contains a location with the name &apos;{1}&apos;. To create this location, please chose another name..
        /// </summary>
        public static string FacilityContainsLocationDescription {
            get {
                return ResourceManager.GetString("FacilityContainsLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Facility with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string FacilityNotFound {
            get {
                return ResourceManager.GetString("FacilityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Facility with Key &apos;{0}&apos; is not of type &apos;{1}&apos;..
        /// </summary>
        public static string FacilityNotOfType {
            get {
                return ResourceManager.GetString("FacilityNotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred which prevented the request from being completed..
        /// </summary>
        public static string GenericFailure {
            get {
                return ResourceManager.GetString("GenericFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [0} Key value is not valid. Value received &apos;{0}&apos;..
        /// </summary>
        public static string GenericInvalidKeyMessage {
            get {
                return ResourceManager.GetString("GenericInvalidKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Grower Company with Key &apos;{0]&apos; was not found..
        /// </summary>
        public static string GrowerCompanyNotFound {
            get {
                return ResourceManager.GetString("GrowerCompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chile Product Ingredient Percentage value must be between 0 and 100..
        /// </summary>
        public static string IngredientPercentageCanIngredientPercentageOutOfRange {
            get {
                return ResourceManager.GetString("IngredientPercentageCanIngredientPercentageOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Instruction with key {&apos;0&apos;} was not found..
        /// </summary>
        public static string InstructionNotFound {
            get {
                return ResourceManager.GetString("InstructionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inter Warehouse Order with Key &apos;{0}&apos; has already been fulfilled..
        /// </summary>
        public static string InterWarehouseOrderAlreadyFulfilled {
            get {
                return ResourceManager.GetString("InterWarehouseOrderAlreadyFulfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The InterWarehouse Order with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string InterWarehouseOrderNotFound {
            get {
                return ResourceManager.GetString("InterWarehouseOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntraWarehouse Order cannot be created between different Warehouses..
        /// </summary>
        public static string IntraWarehouseOrderDifferentWarehouses {
            get {
                return ResourceManager.GetString("IntraWarehouseOrderDifferentWarehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IntraWarehouse Order with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string IntraWarehouseOrderNotFound {
            get {
                return ResourceManager.GetString("IntraWarehouseOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Additive Product Key is not valid..
        /// </summary>
        public static string InvalidAdditiveProductKey {
            get {
                return ResourceManager.GetString("InvalidAdditiveProductKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Additive Type Key is not valid..
        /// </summary>
        public static string InvalidAdditiveTypeKey {
            get {
                return ResourceManager.GetString("InvalidAdditiveTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Attribute Name Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidAttributeNameKey {
            get {
                return ResourceManager.GetString("InvalidAttributeNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Broker Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidBrokerKey {
            get {
                return ResourceManager.GetString("InvalidBrokerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chile Product Attribute Range Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidChileProductAttributeRangeKey {
            get {
                return ResourceManager.GetString("InvalidChileProductAttributeRangeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chile Product Ingredient Key is not valid..
        /// </summary>
        public static string InvalidChileProductIngredientKey {
            get {
                return ResourceManager.GetString("InvalidChileProductIngredientKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chile Product Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidChileProductKey {
            get {
                return ResourceManager.GetString("InvalidChileProductKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chile Type Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidChileTypeKey {
            get {
                return ResourceManager.GetString("InvalidChileTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chile Variety Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidChileVarietyKey {
            get {
                return ResourceManager.GetString("InvalidChileVarietyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company Address Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidCompanyAddressKey {
            get {
                return ResourceManager.GetString("InvalidCompanyAddressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidCompanyKey {
            get {
                return ResourceManager.GetString("InvalidCompanyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company Type Record Key &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidCompanyTypeRecordKey {
            get {
                return ResourceManager.GetString("InvalidCompanyTypeRecordKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contact Address Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidContactAddressKey {
            get {
                return ResourceManager.GetString("InvalidContactAddressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contact Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidContactKey {
            get {
                return ResourceManager.GetString("InvalidContactKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contract Item Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidContractItemKey {
            get {
                return ResourceManager.GetString("InvalidContractItemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contract Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidContractKey {
            get {
                return ResourceManager.GetString("InvalidContractKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidCustomerKey {
            get {
                return ResourceManager.GetString("InvalidCustomerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer Order Item Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidCustomerOrderItemKey {
            get {
                return ResourceManager.GetString("InvalidCustomerOrderItemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer Order Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidCustomerOrderKey {
            get {
                return ResourceManager.GetString("InvalidCustomerOrderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer Order Picked Item Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidCustomerOrderPickedItemKey {
            get {
                return ResourceManager.GetString("InvalidCustomerOrderPickedItemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resolution &apos;{0}&apos; is not valid for defect &apos;{1}&apos;..
        /// </summary>
        public static string InvalidDefectResolutionType {
            get {
                return ResourceManager.GetString("InvalidDefectResolutionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dehydrated Materials Received Item Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidDehydratedMaterialsReceivedItemKey {
            get {
                return ResourceManager.GetString("InvalidDehydratedMaterialsReceivedItemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dehydrated Materials Received Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidDehydratedMaterialsReceivedKey {
            get {
                return ResourceManager.GetString("InvalidDehydratedMaterialsReceivedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Employee Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidEmployeeKey {
            get {
                return ResourceManager.GetString("InvalidEmployeeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Facility Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidFacilityKey {
            get {
                return ResourceManager.GetString("InvalidFacilityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Instruction Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidInstructionKey {
            get {
                return ResourceManager.GetString("InvalidInstructionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Instruction Type Key is not valid..
        /// </summary>
        public static string InvalidInstructionTypeKey {
            get {
                return ResourceManager.GetString("InvalidInstructionTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The InterWarehouse Order Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidInterWarehouseOrderKey {
            get {
                return ResourceManager.GetString("InvalidInterWarehouseOrderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IntraWarehouse Order Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidIntraWarehouseOrderKey {
            get {
                return ResourceManager.GetString("InvalidIntraWarehouseOrderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory Adjustment Item Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidInventoryAdjustmentItemKey {
            get {
                return ResourceManager.GetString("InvalidInventoryAdjustmentItemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory Adjustment Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidInventoryAdjustmentKey {
            get {
                return ResourceManager.GetString("InvalidInventoryAdjustmentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory Item Key is not valid..
        /// </summary>
        public static string InvalidInventoryItemKey {
            get {
                return ResourceManager.GetString("InvalidInventoryItemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory Item Type Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidInventoryItemTypeKey {
            get {
                return ResourceManager.GetString("InvalidInventoryItemTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory Pick Order Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidInventoryPickOrderKey {
            get {
                return ResourceManager.GetString("InvalidInventoryPickOrderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory Quantity By Location Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidInventoryQuantityByLocationKey {
            get {
                return ResourceManager.GetString("InvalidInventoryQuantityByLocationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory Shipment Order Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidInventoryShipmentOrderKey {
            get {
                return ResourceManager.GetString("InvalidInventoryShipmentOrderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory Transaction Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidInventoryTransactionKey {
            get {
                return ResourceManager.GetString("InvalidInventoryTransactionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory Treatment Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidInventoryTreatmentKey {
            get {
                return ResourceManager.GetString("InvalidInventoryTreatmentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Location Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidLocationKey {
            get {
                return ResourceManager.GetString("InvalidLocationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot Attribute Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidLotAttributeKey {
            get {
                return ResourceManager.GetString("InvalidLotAttributeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot Defect Key &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidLotDefectKey {
            get {
                return ResourceManager.GetString("InvalidLotDefectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot Defect Resolution Header Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidLotDefectResolutionHeaderKey {
            get {
                return ResourceManager.GetString("InvalidLotDefectResolutionHeaderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot Defect Resolution Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidLotDefectResolutionKey {
            get {
                return ResourceManager.GetString("InvalidLotDefectResolutionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidLotKey {
            get {
                return ResourceManager.GetString("InvalidLotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot Product Spec Defect Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidLotProductSpecDefectKey {
            get {
                return ResourceManager.GetString("InvalidLotProductSpecDefectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot Type Key is not valid..
        /// </summary>
        public static string InvalidLotTypeKey {
            get {
                return ResourceManager.GetString("InvalidLotTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mill And Wetdown Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidMillAndWetdownKey {
            get {
                return ResourceManager.GetString("InvalidMillAndWetdownKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mill And Wetdown Result Item Key &apos;{0}&apos; it not valid..
        /// </summary>
        public static string InvalidMillAndWetdownResultItemKey {
            get {
                return ResourceManager.GetString("InvalidMillAndWetdownResultItemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Movement InventoryPickOrder Item Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidMovementOrderItemKey {
            get {
                return ResourceManager.GetString("InvalidMovementOrderItemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Movement InventoryPickOrder Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidMovementOrderKey {
            get {
                return ResourceManager.GetString("InvalidMovementOrderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Notebook Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidNotebookKey {
            get {
                return ResourceManager.GetString("InvalidNotebookKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Note Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidNoteKey {
            get {
                return ResourceManager.GetString("InvalidNoteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Packaging Product Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidPackagingProductKey {
            get {
                return ResourceManager.GetString("InvalidPackagingProductKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pack Schedule Number &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidPackScheduleNumber {
            get {
                return ResourceManager.GetString("InvalidPackScheduleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Picked Inventory Item Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidPickedInventoryItemKey {
            get {
                return ResourceManager.GetString("InvalidPickedInventoryItemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Picked Inventory Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidPickedInventoryKey {
            get {
                return ResourceManager.GetString("InvalidPickedInventoryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Product Base Key is not valid..
        /// </summary>
        public static string InvalidProductBaseKey {
            get {
                return ResourceManager.GetString("InvalidProductBaseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Batch Instruction Reference Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidProductionBatchInstructionReferenceKey {
            get {
                return ResourceManager.GetString("InvalidProductionBatchInstructionReferenceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Batch Item Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidProductionBatchItemKey {
            get {
                return ResourceManager.GetString("InvalidProductionBatchItemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Batch Number is not valid..
        /// </summary>
        public static string InvalidProductionBatchLotNumber {
            get {
                return ResourceManager.GetString("InvalidProductionBatchLotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Batch Number &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidProductionBatchNumber {
            get {
                return ResourceManager.GetString("InvalidProductionBatchNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target weight for a production batch must be greater than zero.  Please ensure that Units to Produce is greater than zero and that the packaging item contains a weight greater than zero..
        /// </summary>
        public static string InvalidProductionBatchTargetWeight {
            get {
                return ResourceManager.GetString("InvalidProductionBatchTargetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Location Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidProductionLocationKey {
            get {
                return ResourceManager.GetString("InvalidProductionLocationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Result Item Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidProductionResultItemKey {
            get {
                return ResourceManager.GetString("InvalidProductionResultItemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Result Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidProductionResultKey {
            get {
                return ResourceManager.GetString("InvalidProductionResultKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ProductionScheduleItem key is not valid..
        /// </summary>
        public static string InvalidProductionScheduleItemKey {
            get {
                return ResourceManager.GetString("InvalidProductionScheduleItemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Schedule key is not valid..
        /// </summary>
        public static string InvalidProductionScheduleKey {
            get {
                return ResourceManager.GetString("InvalidProductionScheduleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Product Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidProductKey {
            get {
                return ResourceManager.GetString("InvalidProductKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sales Quote Item Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidSalesQuoteItemKey {
            get {
                return ResourceManager.GetString("InvalidSalesQuoteItemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sales Quote Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidSalesQuoteKey {
            get {
                return ResourceManager.GetString("InvalidSalesQuoteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Shipment Info Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidShipmentInfoKey {
            get {
                return ResourceManager.GetString("InvalidShipmentInfoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Treatment Order Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidTreatmentOrderKey {
            get {
                return ResourceManager.GetString("InvalidTreatmentOrderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Work Type Key &apos;{0}&apos; is not valid..
        /// </summary>
        public static string InvalidWorkTypeKey {
            get {
                return ResourceManager.GetString("InvalidWorkTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Adjustment Items are required..
        /// </summary>
        public static string InventoryAdjustmentItemsRequired {
            get {
                return ResourceManager.GetString("InventoryAdjustmentItemsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory Adjustment with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string InventoryAdjustmentNotFound {
            get {
                return ResourceManager.GetString("InventoryAdjustmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory with Key &apos;{0}&apos; is in an inactive location..
        /// </summary>
        public static string InventoryInactiveLocation {
            get {
                return ResourceManager.GetString("InventoryInactiveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory with Key &apos;{0}&apos; is in invalid Facility &apos;{1}&apos;..
        /// </summary>
        public static string InventoryInvalidFacility {
            get {
                return ResourceManager.GetString("InventoryInvalidFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory item with key &apos;{0}&apos; already exists in database..
        /// </summary>
        public static string InventoryItemAlreadyExists {
            get {
                return ResourceManager.GetString("InventoryItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory Item with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string InventoryItemNotFound {
            get {
                return ResourceManager.GetString("InventoryItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory with Key &apos;{0}&apos; is in a Locked Location..
        /// </summary>
        public static string InventoryLocationLocked {
            get {
                return ResourceManager.GetString("InventoryLocationLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory Pick Order Item with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string InventoryPickOrderItemNotFound {
            get {
                return ResourceManager.GetString("InventoryPickOrderItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory Shipment Order with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string InventoryShipmentOrderNotFound {
            get {
                return ResourceManager.GetString("InventoryShipmentOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory Treatment with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string InventoryTreatmentNotFound {
            get {
                return ResourceManager.GetString("InventoryTreatmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Chile Lot(s) found for Lab Report..
        /// </summary>
        public static string LabReportChileLotsNotFound {
            get {
                return ResourceManager.GetString("LabReportChileLotsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name is required..
        /// </summary>
        public static string LocationDescriptionRequired {
            get {
                return ResourceManager.GetString("LocationDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Location with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string LocationNotFound {
            get {
                return ResourceManager.GetString("LocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot &apos;{0}&apos; attribute &apos;{1}&apos; out of range for {2}..
        /// </summary>
        public static string LotAttributeOutOfRequiredRange {
            get {
                return ResourceManager.GetString("LotAttributeOutOfRequiredRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot &apos;{0}&apos; is either treated or pending treatment with a conflicting treatment type. A lot cannot receive multiple treatment types..
        /// </summary>
        public static string LotConflictingInventoryTreatment {
            get {
                return ResourceManager.GetString("LotConflictingInventoryTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Date Sequence number should be greater than 0..
        /// </summary>
        public static string LotDateSequenceLessThanOne {
            get {
                return ResourceManager.GetString("LotDateSequenceLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot Defect with Key &apos;{0}&apos; has no Resolution..
        /// </summary>
        public static string LotDefectHasNoResolution {
            get {
                return ResourceManager.GetString("LotDefectHasNoResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot Defect with Key &apos;{0}&apos; already has a resolution..
        /// </summary>
        public static string LotDefectHasResolution {
            get {
                return ResourceManager.GetString("LotDefectHasResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot Defect with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string LotDefectNotFound {
            get {
                return ResourceManager.GetString("LotDefectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Lot with Key &apos;{0}&apos; already exists..
        /// </summary>
        public static string LotExistsWithKey {
            get {
                return ResourceManager.GetString("LotExistsWithKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot with Key &apos;{0}&apos; has exisiting Inventory..
        /// </summary>
        public static string LotHasExistingInventory {
            get {
                return ResourceManager.GetString("LotHasExistingInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot with Key &apos;{0}&apos; has been picked..
        /// </summary>
        public static string LotHasExistingPickedInventory {
            get {
                return ResourceManager.GetString("LotHasExistingPickedInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot &apos;{0}&apos; missing value for attribute &apos;{1}&apos; required by {2}..
        /// </summary>
        public static string LotMissingRequiredAttribute {
            get {
                return ResourceManager.GetString("LotMissingRequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string LotNotFound {
            get {
                return ResourceManager.GetString("LotNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mill and Wetdown Entry with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string MillAndWetdownEntryNotFound {
            get {
                return ResourceManager.GetString("MillAndWetdownEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mill and Wetdown entry requires Picked Inventory Items..
        /// </summary>
        public static string MillAndWetdownPickedRequired {
            get {
                return ResourceManager.GetString("MillAndWetdownPickedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mill and Wetdown entry requires results..
        /// </summary>
        public static string MillAndWetdownResultsRequired {
            get {
                return ResourceManager.GetString("MillAndWetdownResultsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested changes could not be performed because the following lots would have negative inventory: {0}.
        /// </summary>
        public static string NegativeInventoryLots {
            get {
                return ResourceManager.GetString("NegativeInventoryLots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging Weight must be greater than or equal to 0..
        /// </summary>
        public static string NegativePackagingWeight {
            get {
                return ResourceManager.GetString("NegativePackagingWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet weight must be greater than or equal to 0..
        /// </summary>
        public static string NegativePalletWeight {
            get {
                return ResourceManager.GetString("NegativePalletWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight must be greater than or equal to 0..
        /// </summary>
        public static string NegativeWeight {
            get {
                return ResourceManager.GetString("NegativeWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active Customer Product Range found for Customer with Key &apos;{0}&apos; for Chile Product with Key &apos;{1}&apos;..
        /// </summary>
        public static string NoCustomerProductRangesFound {
            get {
                return ResourceManager.GetString("NoCustomerProductRangesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Non-Inventory Product with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string NonInventoryProductNotFound {
            get {
                return ResourceManager.GetString("NonInventoryProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;No Packaging&apos; product not found..
        /// </summary>
        public static string NoPackagingNotFound {
            get {
                return ResourceManager.GetString("NoPackagingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all attributes for Lot with Key &apos;{0}&apos; accounted for..
        /// </summary>
        public static string NotAllLotAttributesAccountedFor {
            get {
                return ResourceManager.GetString("NotAllLotAttributesAccountedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot with Key &apos;{0}&apos; is not a Chile Lot..
        /// </summary>
        public static string NotChileLot {
            get {
                return ResourceManager.GetString("NotChileLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Notebook with Key &apos;{0}&apos; was not be found..
        /// </summary>
        public static string NotebookNotFound {
            get {
                return ResourceManager.GetString("NotebookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Note with Key &apos;{0}&apos; was not be found..
        /// </summary>
        public static string NoteNotFound {
            get {
                return ResourceManager.GetString("NoteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection of Inventory Keys and Quantities was null or empty..
        /// </summary>
        public static string NullOrEmptyInventoryKeysAndQuantities {
            get {
                return ResourceManager.GetString("NullOrEmptyInventoryKeysAndQuantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only In-House contaminations can be created..
        /// </summary>
        public static string OnlyInHouseContaminationValid {
            get {
                return ResourceManager.GetString("OnlyInHouseContaminationValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Packaging Product with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string PackagingProductNotFound {
            get {
                return ResourceManager.GetString("PackagingProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Chile Product must result in the same Lot type..
        /// </summary>
        public static string PackScheduleChileProductDifferentLotType {
            get {
                return ResourceManager.GetString("PackScheduleChileProductDifferentLotType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PackSchedule with Key &apos;{0}&apos; has been scheduled for production..
        /// </summary>
        public static string PackScheduleHasBeenScheduled {
            get {
                return ResourceManager.GetString("PackScheduleHasBeenScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pack Schedule with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string PackScheduleNotFound {
            get {
                return ResourceManager.GetString("PackScheduleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Batch for Lot &apos;{0}&apos; has already been completed. The Pack Schedule cannot be deleted once any of the batches have been completed..
        /// </summary>
        public static string PackScheduleRemoveFail_LotCompleted {
            get {
                return ResourceManager.GetString("PackScheduleRemoveFail_LotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Picked Inventory Item&apos;s Destination Location does not belong to the Facility with Key &apos;{0}&apos;..
        /// </summary>
        public static string PickedDestinationNotOfFacility {
            get {
                return ResourceManager.GetString("PickedDestinationNotOfFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PickedInventory record with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string PickedInventory {
            get {
                return ResourceManager.GetString("PickedInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Picked Inventory Item with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string PickedInventoryItemNotFound {
            get {
                return ResourceManager.GetString("PickedInventoryItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Picked Inventory Item with Key &apos;{0}&apos; is not in it&apos;s original location..
        /// </summary>
        public static string PickedInventoryItemNotInOriginalLocation {
            get {
                return ResourceManager.GetString("PickedInventoryItemNotInOriginalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must supply a picked items manifest for this operation..
        /// </summary>
        public static string PickedItemsManifestRequired {
            get {
                return ResourceManager.GetString("PickedItemsManifestRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Batch with Key &apos;{0}&apos; has already been completed..
        /// </summary>
        public static string ProductionBatchAlreadyComplete {
            get {
                return ResourceManager.GetString("ProductionBatchAlreadyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Batch with Key &apos;{0}&apos; has Production Results..
        /// </summary>
        public static string ProductionBatchHasResult {
            get {
                return ResourceManager.GetString("ProductionBatchHasResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Batch Item with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ProductionBatchItemNotFound {
            get {
                return ResourceManager.GetString("ProductionBatchItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Batch with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ProductionBatchNotFound {
            get {
                return ResourceManager.GetString("ProductionBatchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Batch must produce at least one packaging unit..
        /// </summary>
        public static string ProductionBatchNumberOfPackagingUnitsRequired {
            get {
                return ResourceManager.GetString("ProductionBatchNumberOfPackagingUnitsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Location with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ProductionLocationNotFound {
            get {
                return ResourceManager.GetString("ProductionLocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Result for Inventory with key &apos;{0}&apos; is already pending addition..
        /// </summary>
        public static string ProductionResultAlreadyPendingAddition {
            get {
                return ResourceManager.GetString("ProductionResultAlreadyPendingAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Result Item with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ProductionResultItemNotFound {
            get {
                return ResourceManager.GetString("ProductionResultItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Result with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ProductionResultNotFound {
            get {
                return ResourceManager.GetString("ProductionResultNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Schedule for &apos;{0}&apos; on &apos;{1}&apos; already exists..
        /// </summary>
        public static string ProductionScheduleAlreadyExists {
            get {
                return ResourceManager.GetString("ProductionScheduleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Schedule Item with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ProductionScheduleItemNotFound {
            get {
                return ResourceManager.GetString("ProductionScheduleItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must supply a Production Schedule Items manifest for this operation..
        /// </summary>
        public static string ProductionScheduleItemsManifestRequired {
            get {
                return ResourceManager.GetString("ProductionScheduleItemsManifestRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Production Schedule with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ProductionScheduleNotFound {
            get {
                return ResourceManager.GetString("ProductionScheduleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Product with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Spec.
        /// </summary>
        public static string ProductSpec {
            get {
                return ResourceManager.GetString("ProductSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Quantity for Inventory with Key &apos;{0}&apos; cannot be negative..
        /// </summary>
        public static string QuantityForInventoryCannotbeNegative {
            get {
                return ResourceManager.GetString("QuantityForInventoryCannotbeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Quantity for Inventory with Key &apos;{0}&apos; must be greater than 0..
        /// </summary>
        public static string QuantityForInventoryMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("QuantityForInventoryMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Quantity for Picked Inventory Item with Key &apos;{0}&apos; cannot be negative..
        /// </summary>
        public static string QuantityForPickedCannotBeNegative {
            get {
                return ResourceManager.GetString("QuantityForPickedCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Quantity for picking from Inventory with Key &apos;{0}&apos; must be greater than 0..
        /// </summary>
        public static string QuantityForPickingFromInventoryMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("QuantityForPickingFromInventoryMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity cannot be negative..
        /// </summary>
        public static string QuantityIsNegative {
            get {
                return ResourceManager.GetString("QuantityIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity supplied must be greater than 0..
        /// </summary>
        public static string QuantityNotGreaterThanZero {
            get {
                return ResourceManager.GetString("QuantityNotGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Defect Resolution requires Description..
        /// </summary>
        public static string ResolutionDescriptionRequired {
            get {
                return ResourceManager.GetString("ResolutionDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sales Order with Key &apos;{0}&apos; has already been fulfilled..
        /// </summary>
        public static string SalesOrderAlreadyFulfilled {
            get {
                return ResourceManager.GetString("SalesOrderAlreadyFulfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item references a Contract with a different Broker than the Sales Order..
        /// </summary>
        public static string SalesOrderItemBrokerConflict {
            get {
                return ResourceManager.GetString("SalesOrderItemBrokerConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sales Order Item with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string SalesOrderItemNotFound {
            get {
                return ResourceManager.GetString("SalesOrderItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sales Order with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string SalesOrderNotFound {
            get {
                return ResourceManager.GetString("SalesOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sales Order with Key &apos;{0}&apos; has not been shipped..
        /// </summary>
        public static string SalesOrderNotShipped {
            get {
                return ResourceManager.GetString("SalesOrderNotShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sales Order Picked Item with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string SalesOrderPickedItemNotFound {
            get {
                return ResourceManager.GetString("SalesOrderPickedItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sales Quote Item with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string SalesQuoteItemNotFound {
            get {
                return ResourceManager.GetString("SalesQuoteItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sales Quote with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string SalesQuoteNotFound_Key {
            get {
                return ResourceManager.GetString("SalesQuoteNotFound_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sales Quote with Number &apos;{0}&apos; was not found..
        /// </summary>
        public static string SalesQuoteNotFound_Num {
            get {
                return ResourceManager.GetString("SalesQuoteNotFound_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Quote Number is required..
        /// </summary>
        public static string SalesQuoteNumberRequired {
            get {
                return ResourceManager.GetString("SalesQuoteNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sample Order Item with Key &apos;{0}&apos; could not be found..
        /// </summary>
        public static string SampleOrderItemNotFound {
            get {
                return ResourceManager.GetString("SampleOrderItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sample Order Journal Entry with Key &apos;{0}&apos; could not be found..
        /// </summary>
        public static string SampleOrderJournalEntryNotFound {
            get {
                return ResourceManager.GetString("SampleOrderJournalEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sample Order with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string SampleOrderNotFound {
            get {
                return ResourceManager.GetString("SampleOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot post shipment with status &apos;{0}&apos;..
        /// </summary>
        public static string ShipmentStatusCannotPost {
            get {
                return ResourceManager.GetString("ShipmentStatusCannotPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source location must be in Facility with Key &apos;{0}&apos;..
        /// </summary>
        public static string SourceLocationMustBelongToFacility {
            get {
                return ResourceManager.GetString("SourceLocationMustBelongToFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Supplier Company with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string SupplierCompanyNotFound {
            get {
                return ResourceManager.GetString("SupplierCompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tote Key &apos;{0}&apos; cannot contain invalid character &apos;{1}&apos;..
        /// </summary>
        public static string ToteKeyInvalidCharacter {
            get {
                return ResourceManager.GetString("ToteKeyInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tote Keys collection cannot be empty..
        /// </summary>
        public static string ToteKeysCollectionCannotBeEmpty {
            get {
                return ResourceManager.GetString("ToteKeysCollectionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Treatment &apos;{0}&apos; on Inventory Item with Key &apos;{1}&apos; does not resolve Lot defect for attribute &apos;{2}&apos;..
        /// </summary>
        public static string TreatmentOnInventoryDoesNotResolveDefect {
            get {
                return ResourceManager.GetString("TreatmentOnInventoryDoesNotResolveDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Treatment &apos;{0}&apos; on unarchived Picked Inventory Item with Key &apos;{1}&apos; does not resolve Lot defect for attribute &apos;{2}&apos;..
        /// </summary>
        public static string TreatmentOnUnarchivedPickedInventoryDoesNotResolveDefect {
            get {
                return ResourceManager.GetString("TreatmentOnUnarchivedPickedInventoryDoesNotResolveDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Treatment Order with Key &apos;{0}&apos; has already been fulfilled..
        /// </summary>
        public static string TreatmentOrderAlreadyFulfilled {
            get {
                return ResourceManager.GetString("TreatmentOrderAlreadyFulfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Treatment Order with Key &apos;{0}&apos; was not found..
        /// </summary>
        public static string TreatmentOrderNotFound {
            get {
                return ResourceManager.GetString("TreatmentOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must supply user for this operation..
        /// </summary>
        public static string UserRequired {
            get {
                return ResourceManager.GetString("UserRequired", resourceCulture);
            }
        }
    }
}
