//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioValleyChili.Services.OldContextSynchronization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConsoleOutput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleOutput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RioValleyChili.Services.OldContextSynchronization.ConsoleOutput", typeof(ConsoleOutput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new tblAdjust[{0}] record..
        /// </summary>
        public static string AddedAdjust {
            get {
                return ResourceManager.GetString("AddedAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new tblLot[{0}] record..
        /// </summary>
        public static string AddedLot {
            get {
                return ResourceManager.GetString("AddedLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new tblPackSch[{0}] record..
        /// </summary>
        public static string AddedPackSchedule {
            get {
                return ResourceManager.GetString("AddedPackSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed {0} expired contracts..
        /// </summary>
        public static string CompletedExpiredContracts {
            get {
                return ResourceManager.GetString("CompletedExpiredContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Contact[{0}] record..
        /// </summary>
        public static string DeletedContact {
            get {
                return ResourceManager.GetString("DeletedContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted tblLot[{0}] record(s)..
        /// </summary>
        public static string DeletedTblLot {
            get {
                return ResourceManager.GetString("DeletedTblLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted tblProfile[{0}] record..
        /// </summary>
        public static string DeletedTblProfile {
            get {
                return ResourceManager.GetString("DeletedTblProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted tblSample[{0}] record(s)..
        /// </summary>
        public static string DeletedTblSample {
            get {
                return ResourceManager.GetString("DeletedTblSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoiced tblOrder[{0}] record..
        /// </summary>
        public static string InvoicedOrder {
            get {
                return ResourceManager.GetString("InvoicedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No expired contracts to complete..
        /// </summary>
        public static string NoExpiredContracts {
            get {
                return ResourceManager.GetString("NoExpiredContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted order[{0}]..
        /// </summary>
        public static string PostedOrder {
            get {
                return ResourceManager.GetString("PostedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created tblLot[{0}] with tblIncoming records..
        /// </summary>
        public static string ReceivedInventory {
            get {
                return ResourceManager.GetString("ReceivedInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received tblMove[{0}] treatment order..
        /// </summary>
        public static string ReceivedTreatmentOrder {
            get {
                return ResourceManager.GetString("ReceivedTreatmentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed tblContract[{0}] and tblContractDetail record(s)..
        /// </summary>
        public static string RemovedContract {
            get {
                return ResourceManager.GetString("RemovedContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed tblPackSch[{0}] record..
        /// </summary>
        public static string RemovedPackSchedule {
            get {
                return ResourceManager.GetString("RemovedPackSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed production batch records for tblLot[{0}] record..
        /// </summary>
        public static string RemovedProductionBatch {
            get {
                return ResourceManager.GetString("RemovedProductionBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed tblMove[{0}] record..
        /// </summary>
        public static string RemovedTblMove {
            get {
                return ResourceManager.GetString("RemovedTblMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed tblOrder[{0}] record..
        /// </summary>
        public static string RemovedTblOrder {
            get {
                return ResourceManager.GetString("RemovedTblOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set picked inventory items for tblLot[{0}] record..
        /// </summary>
        public static string SetPickedItemsForLot {
            get {
                return ResourceManager.GetString("SetPickedItemsForLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set shipment for tblMove[{0}] record..
        /// </summary>
        public static string SetShipmentTblMove {
            get {
                return ResourceManager.GetString("SetShipmentTblMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set shipment for tblOrder[{0}] record..
        /// </summary>
        public static string SetShipmentTblOrder {
            get {
                return ResourceManager.GetString("SetShipmentTblOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized tblContract[{0}] statuses..
        /// </summary>
        public static string SyncContractsStatus {
            get {
                return ResourceManager.GetString("SyncContractsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized dehydrated received for tblLot[{0}]..
        /// </summary>
        public static string SyncDehydratedReceived {
            get {
                return ResourceManager.GetString("SyncDehydratedReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized tblWarehouse[{0}] record..
        /// </summary>
        public static string SyncFacility {
            get {
                return ResourceManager.GetString("SyncFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synched Company[{0}] record..
        /// </summary>
        public static string SynchedCompany {
            get {
                return ResourceManager.GetString("SynchedCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synched tblPackaging[{0}] record..
        /// </summary>
        public static string SynchedTblPackaging {
            get {
                return ResourceManager.GetString("SynchedTblPackaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synched tblProduct[{0}] record..
        /// </summary>
        public static string SynchedTblProduct {
            get {
                return ResourceManager.GetString("SynchedTblProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized tblSample[{0}] record(s)..
        /// </summary>
        public static string SynchedTblSample {
            get {
                return ResourceManager.GetString("SynchedTblSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized tblContract[{0}] record..
        /// </summary>
        public static string SynchronizedContract {
            get {
                return ResourceManager.GetString("SynchronizedContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized tblRincon[{0}] record..
        /// </summary>
        public static string SynchronizedIntraWarehouserMovement {
            get {
                return ResourceManager.GetString("SynchronizedIntraWarehouserMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized tblLocation[{0}]..
        /// </summary>
        public static string SyncLocation {
            get {
                return ResourceManager.GetString("SyncLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized production results for tblLot[{0}] record..
        /// </summary>
        public static string SyncProductionResults {
            get {
                return ResourceManager.GetString("SyncProductionResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synched ProudctionSchedule[{0}-{1}] record..
        /// </summary>
        public static string SyncProductionSchedule {
            get {
                return ResourceManager.GetString("SyncProductionSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized tblMove[{0}] record..
        /// </summary>
        public static string SyncTblMove {
            get {
                return ResourceManager.GetString("SyncTblMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized tblOrder[{0}] record..
        /// </summary>
        public static string SyncTblOrder {
            get {
                return ResourceManager.GetString("SyncTblOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized tblProductIngrs records for ProdID[{0}]..
        /// </summary>
        public static string SyncTblProductIngrs {
            get {
                return ResourceManager.GetString("SyncTblProductIngrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synched tblQuote[{0}] record..
        /// </summary>
        public static string SyncTblQuote {
            get {
                return ResourceManager.GetString("SyncTblQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated tblBatchInstr for tblLot[{0}] record..
        /// </summary>
        public static string UpdatedBatchInstructions {
            get {
                return ResourceManager.GetString("UpdatedBatchInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated spec for customer[{0}] product[{1}]..
        /// </summary>
        public static string UpdatedCustomerSpecs {
            get {
                return ResourceManager.GetString("UpdatedCustomerSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated tblLot[{0}] record..
        /// </summary>
        public static string UpdatedLot {
            get {
                return ResourceManager.GetString("UpdatedLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated tblPackSch[{0}] record..
        /// </summary>
        public static string UpdatedPackSchedule {
            get {
                return ResourceManager.GetString("UpdatedPackSchedule", resourceCulture);
            }
        }
    }
}
