// <auto-generated />
namespace RioValleyChili.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MillAndWetdownLotTrim : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MillAndWetdownLotTrim));
        
        string IMigrationMetadata.Id
        {
            get { return "201311041830271_MillAndWetdownLotTrim"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
