// <auto-generated />
namespace RioValleyChili.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class InventoryPickOrderItem_DropTreatment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InventoryPickOrderItem_DropTreatment));
        
        string IMigrationMetadata.Id
        {
            get { return "201307241645307_InventoryPickOrderItem_DropTreatment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
