// <auto-generated />
namespace RioValleyChili.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LotAttributeAndResolution_EmployeeBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LotAttributeAndResolution_EmployeeBase));
        
        string IMigrationMetadata.Id
        {
            get { return "201402241849433_LotAttributeAndResolution_EmployeeBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
