// <auto-generated />
namespace RioValleyChili.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PackScheduleDeploy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PackScheduleDeploy));
        
        string IMigrationMetadata.Id
        {
            get { return "201403251810300_PackScheduleDeploy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
