// <auto-generated />
namespace RioValleyChili.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PackSchedule_PSNum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PackSchedule_PSNum));
        
        string IMigrationMetadata.Id
        {
            get { return "201404072101555_PackSchedule_PSNum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
