// <auto-generated />
namespace RioValleyChili.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ProductionResults_Employee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductionResults_Employee));
        
        string IMigrationMetadata.Id
        {
            get { return "201401282118043_ProductionResults_Employee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
