// <auto-generated />
namespace RioValleyChili.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LotProductSpecStatuses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LotProductSpecStatuses));
        
        string IMigrationMetadata.Id
        {
            get { return "201405281459038_LotProductSpecStatuses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
