// <auto-generated />
namespace RioValleyChili.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DataLoadResult_TimeStamp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataLoadResult_TimeStamp));
        
        string IMigrationMetadata.Id
        {
            get { return "201401211809443_DataLoadResult_TimeStamp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
