// <auto-generated />
namespace RioValleyChili.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Facility_WHID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Facility_WHID));
        
        string IMigrationMetadata.Id
        {
            get { return "201503022154482_Facility_WHID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
