// <auto-generated />
namespace RioValleyChili.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ChileProductIngredients_EmployeeIdentifiable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChileProductIngredients_EmployeeIdentifiable));
        
        string IMigrationMetadata.Id
        {
            get { return "201608302241323_ChileProductIngredients_EmployeeIdentifiable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
