// <auto-generated />
namespace RioValleyChili.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ShipmentInformation_ShipmentDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShipmentInformation_ShipmentDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201608292036420_ShipmentInformation_ShipmentDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
