// <auto-generated />
namespace RioValleyChili.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ChileProduct_IngredientsDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChileProduct_IngredientsDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201611072128073_ChileProduct_IngredientsDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
